# site settings
title: Halloween On Hill Top
subtitle:
email: hello@halloweenonhilltop.uk
description: A family-run Haloween scare house in Manchester, England
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.halloweenonhilltop.uk" # the base hostname & protocol for your site
author:
street_address: 21 Hill Top Avenue
city: Cheadle Hulme
state: Cheshire
zip_code: SK8 7HN
country: United Kingdom
phone:
messenger: HalloweenOnHillTop
donations-url: "https://fundraise.cancerresearchuk.org/page/halloween-on-hill-top-2021"

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  Facebook: https://www.facebook.com/HalloweenOnHillTop

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
